import {
  sqliteTable,
  text,
  index,
} from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";
import { traders } from "~/features/traders/database/schema";

/**
 * Analysis records table
 * Stores analysis content and structured data generated by analysis team members (roles)
 */
export const analysisRecords = sqliteTable(
  "analysis_records",
  {
    // Primary key
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    // Associated trader
    traderId: text("trader_id")
      .notNull()
      .references(() => traders.id, { onDelete: "restrict" }),
    // Role within the analysis team (e.g., technical analyst, fundamental analyst, risk manager, etc.)
    role: text("role").notNull(),
    // Generated analysis content
    chat: text("chat").notNull(),
    // Structured data (JSON string)
    jsonValue: text("json_value"),
    // Round ID, can be null
    recordId: text("record_id"),
    // Order ID
    orderId: text("order_id"),
    // Created at timestamp
    createdAt: text("created_at")
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
    // Updated at timestamp
    updatedAt: text("updated_at")
      .notNull()
      .$defaultFn(() => new Date().toISOString()),
  },
  (table) => ({
    // Index for querying by trader and time
    traderTimeIdx: index("idx_analysis_records_trader_created").on(
      table.traderId,
      table.createdAt
    ),
    // Index for querying by role
    roleIdx: index("idx_analysis_records_role").on(table.role),
  })
);

export const insertAnalysisRecordSchema = createInsertSchema(analysisRecords, {
  traderId: () => z.string().min(1),
  role: () => z.string().min(1),
  chat: () => z.string().min(1),
  jsonValue: () => z.string().optional(),
  recordId: () => z.string().optional(),
  createdAt: () => z.string().datetime().optional(),
});

export const selectAnalysisRecordSchema = createSelectSchema(analysisRecords);
