import type { ActionFunctionArgs } from "react-router";
import { getEnvContext } from "~/context";
import { createPositionRecord } from "~/features/positions/api/handlers";
import { insertPositionRecordSchema } from "~/features/positions/database/schema";

function getDeps(context: ActionFunctionArgs["context"]) {
  const { db } = getEnvContext(context);
  return { db };
}

export async function action({ request, context }: ActionFunctionArgs) {
  // Authentication
  // const authResult = await authenticate(request, context);
  // if (!authResult.success) {
  //   return Response.json(
  //     {
  //       success: false,
  //       error: authResult.error?.message ?? "Unauthorized",
  //       code: authResult.error?.code ?? "UNAUTHORIZED",
  //     },
  //     { status: 401 }
  //   );
  // }

  // setUserContext(context, authResult.user);

  // Only handle POST requests
  if (request.method !== "POST") {
    return Response.json(
      {
        success: false,
        error: "Method not allowed",
        code: "METHOD_NOT_ALLOWED",
      },
      { status: 405 }
    );
  }

  const deps = getDeps(context);

  try {
    // Parse request body
    const body = (await request.json()) as Record<string, unknown>;

    // If positions is an array, convert to JSON string
    if (Array.isArray(body.positions)) {
      body.positions = JSON.stringify(body.positions);
    }

    // Validate data
    const validationResult = insertPositionRecordSchema.safeParse({
      ...body,
      id: undefined, // id is auto-generated by database
      createdAt: body.createdAt || undefined, // Optional, uses database default
      updatedAt: body.updatedAt || undefined, // Get from request
    });

    if (!validationResult.success) {
      return Response.json(
        {
          success: false,
          error: "Invalid request data",
          code: "VALIDATION_ERROR",
          details: validationResult.error.flatten(),
        },
        { status: 400 }
      );
    }

    // Create position record
    const record = await createPositionRecord(deps.db, {
      traderId: validationResult.data.traderId,
      recordId: validationResult.data.recordId ?? null,
      positions: validationResult.data.positions,
      accountBalance: validationResult.data.accountBalance,
      createdAt: validationResult.data.createdAt,
      updatedAt: validationResult.data.updatedAt,
    });

    return Response.json(
      {
        success: true,
        data: record,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Failed to create position record:", error);
    return Response.json(
      {
        success: false,
        error:
          error instanceof Error ? error.message : "Failed to create position record",
        code: "CREATE_FAILED",
      },
      { status: 500 }
    );
  }
}
