import type { ActionFunctionArgs } from "react-router";
import { getEnvContext } from "~/context";
import { authenticate, setUserContext } from "~/middleware/common";
import { createTrader } from "~/features/traders/api/handlers";
import { insertTraderSchema } from "~/features/traders/database/schema";

function getDeps(context: ActionFunctionArgs["context"]) {
  const { db } = getEnvContext(context);
  return { db };
}

export async function action({ request, context }: ActionFunctionArgs) {
  // Authentication
  const authResult = await authenticate(request, context);
  if (!authResult.success) {
    return Response.json(
      {
        success: false,
        error: authResult.error?.message ?? "Unauthorized",
        code: authResult.error?.code ?? "UNAUTHORIZED",
      },
      { status: 401 }
    );
  }

  setUserContext(context, authResult.user);

  // Only handle POST requests
  if (request.method !== "POST") {
    return Response.json(
      {
        success: false,
        error: "Method not allowed",
        code: "METHOD_NOT_ALLOWED",
      },
      { status: 405 }
    );
  }

  const deps = getDeps(context);

  try {
    // Parse request body
    const body = (await request.json()) as Record<string, unknown>;

    // Validate data
    const validationResult = insertTraderSchema.safeParse({
      ...body,
      id: undefined, // id is auto-generated by database
      createdAt: undefined, // Auto-set by database
      updatedAt: undefined, // Auto-set by database
    });

    if (!validationResult.success) {
      return Response.json(
        {
          success: false,
          error: "Invalid request data",
          code: "VALIDATION_ERROR",
          details: validationResult.error.flatten(),
        },
        { status: 400 }
      );
    }

    // Create trader
    const trader = await createTrader(deps.db, {
      name: validationResult.data.name,
      description: validationResult.data.description ?? undefined,
    });

    return Response.json(
      {
        success: true,
        data: trader,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Failed to create trader:", error);
    return Response.json(
      {
        success: false,
        error:
          error instanceof Error ? error.message : "Failed to create trader",
        code: "CREATE_FAILED",
      },
      { status: 500 }
    );
  }
}

